### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by iqualfragile** [qrlpx/unsafe_unions#1]
Hi, currently this does not compile.
Compiling it with the latest interpolate_idents work, from git that is.
so most likely you will have to update the requirements to use version 0.0.9, which is not released yet

**Comment by qrlpx** [comment]
Sorry for the late answer, didn't realize anyone was actually looking at the stuff I'm putting out.

If there's still interest, I've reworked the lib and got rid off the fickle interpolate_idents-dep completly.
Not only that, the lib now also runs on stable & no_std.

Downside is, it's now a bit weirder to execute the different ops: instead of differently named functions, you now get different "modes", each mode for one op.

`.get_foo() => .by_ref().foo()`
`.get_foo_mut() => .by_mut().foo()`
`.read_foo() => .read().foo()`
`.write_foo(x) => .write().foo(x)`

**Comment by iqualfragile** [comment]
Thank you.
Have you done some benchmarks on how the two function calls change performace characteristics?
